### PR TITLE
Supporting comments

### PR DESCRIPTION
**Pull request by igorkramaric**
#27

A note: was looking for the best way to fit comments in the _grammar_. While checking this I realized they actually belong to pre-grammar check, as a part of lexical analysis. This way we keep grammar to keep doing its work. Downside is that `PrettyPrint` won't be able to handle comments. Comments would not be lost since we don't use `PrettyPrint` for user side data.

Not sure if this is fine.  Plus, at one point I did it with C/C++ style comments, [here](https://github.com/mediapredict/daffodil/commit/1fcf7bd335a2939d6daf585606c31dfae32c5457) is a commit containing such implementation + tests. Just mentioning it - maybe these could be used?

### CODE REVIEW

**Comment by jiaaro** [comment]
comments should pass through pretty print - if pretty print removes comments, it will never be used

**Comment by mpmarc** [comment]
I merged PR #28 without checking for a version number change in setup.py.  Please include a version number update in this PR and make sure to change requirements.txt to match for KF/MP/Dialator.

**Comment by igorkramaric** [comment]
New daff ver. included here. At the same time Daffodil [ver. is upgraded](https://github.com/mediapredict/daffodil/pull/29/commits/e765a8cd271258beca80cdfb34e96b59a53d2457).

**Comment by mpmarc** [comment]
I tried this:
>>> s = '''
{
  # This is the first comment
x < 10 # This is the second comment
}
'''

>>> s

'\n{\n  # This is the first comment\nx < 10 # This is the second comment\n}\n'
>>> print  Daffodil(s, delegate=PrettyPrintDelegate(dense=False))()
print  Daffodil(s, delegate=PrettyPrintDelegate(dense=False))()
{
  # This is the first comment
  "x" < 10
  # This is the second comment
}
>>> 

The second comment is not in the right place on the pretty print.

**Pull request merged**
